package com.java.exceptionhandling;

public class ZE {

	public static void main(String[]args){
		
		try{
			
		}
		catch(ArithmeticException ae){
			int i=10;
		}
	//System.out.println(i);
	// these statement doesnot belongs to either try or catch , these i variable out of try and catch blocks ....
	}
}
